[package]
name = "pikmin"
version = "0.1.0"
edition = "2021"
author = "BM"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
int-enum = "0.4.0"
enum-iterator = "0.7.0"